# Generated by Django 4.2.1 on 2023-06-01 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='sname',
        ),
    ]
