# Generated by Django 4.2.2 on 2023-06-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('standard', models.IntegerField()),
                ('division', models.CharField(max_length=1)),
            ],
        ),
    ]
