# Generated by Django 4.2.2 on 2023-06-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.ImageField(upload_to='mypics/')),
            ],
        ),
        migrations.DeleteModel(
            name='pics',
        ),
    ]
