# Generated by Django 4.2.2 on 2023-06-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pics',
            field=models.FileField(upload_to='pics/'),
        ),
    ]
