# Generated by Django 4.2.2 on 2023-06-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apz', '0002_alter_book_pdf_alter_book_pics'),
    ]

    operations = [
        migrations.CreateModel(
            name='formdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('em', models.EmailField(max_length=20)),
                ('feedback', models.CharField(max_length=20)),
            ],
        ),
    ]
