# Generated by Django 4.2.3 on 2023-07-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indx', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('scourse', models.CharField(max_length=20)),
            ],
        ),
    ]
