# Generated by Django 4.2.3 on 2023-07-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('names', models.CharField(max_length=20)),
                ('courses', models.CharField(max_length=20)),
            ],
        ),
    ]
